version: 0.2

phases:
  install:
    commands:
      - curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - cd terraform/$TF_EXEC_PATH
      - terraform init
      - terraform plan
